version: "3.9"

services:
  colorwheel:
    restart: "unless-stopped"
    container_name: "colorwheel"
    build:
      context: ./
      dockerfile: "docker/Dockerfile"
    command: >
      sh -c "jupyter nbconvert --to python src/frontend.ipynb &&
             python src/frontend.py"
    volumes:
      - ./src:/app/work/src
    ports:
      - "8050:8050"