version: "3"

services:
  colorwheel:
    restart: "unless-stopped"
    container_name: "colorwheel"
    build:
      context: ./
      dockerfile: "docker/Dockerfile"
    command: "python src/frontend.py"
    volumes:
      - "Volumes/RAMDisk:/Volumes/RAMDisk"
    ports:
      - "8091:8091"