version: "3"

services:
  colorwheel:
    restart: "unless-stopped"
    container_name: "colorwheel"
    build:
      context: ./
      dockerfile: "docker/Dockerfile"
    command: "python src/frontend.py"
    volumes:
      - ram_vol:/Volumes/RAMDisk
    ports:
      - "8091:8091"
      
volumes:
    ram_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs